package com.izivia.ocpp.operation.information

enum class ActionOcpp(val value: String) {
    RESET("Reset"),
    SET_VARIABLES("etVariables"),
    CHANGE_AVAILABILITY("ChangeAvailability"),
    CLEAR_CACHE	("ClearCache"),
    REQUEST_START_TRANSACTION("RequestStartTransaction"),
    REQUEST_STOP_TRANSACTION("RequestStopTransaction"),
    UNLOCK_CONNECTOR("UnlockConnector"),
    GET_REPORT("GetReport"),
    GET_BASE_REPORT("GetBaseReport"),
    GET_VARIABLES("GetVariables"),
    CANCEL_RESERVATION("CancelReservation"),
    CLEAR_CHARGING_PROFILE("ClearChargingProfile"),
    GET_COMPOSITE_SCHEDULE("GetCompositeSchedule"),
    GET_LOCAL_LIST_VERSION("GetLocalListVersion"),
    UPDATE_FIRMWARE("UpdateFirmware"),
    SEND_LOCAL_LIST("SendLocalList"),
    TRIGGER_MESSAGE("TriggerMessage"),
    SET_CHARGING_PROFILE("SetChargingProfile"),
    RESERVE_NOW("ReserveNow"),
    DATA_TRANSFER("DataTransfer"),
    CERTIFICATE_SIGNED("CertificateSigned"),
    GET_LOG("GetLog"),
    CLEAR_DISPLAY_MESSAGE("ClearDisplayMessage"),
    GET_CHARGING_PROFILES("GetChargingProfiles"),
    GET_INSTALLED_CERTIFICATE_IDS("GetInstalledCertificateIds"),
    INSTALL_CERTIFICATE("InstallCertificate"),
    CUSTOMER_INFORMATION("CustomerInformation"),
    UNPUBLISH_FIRMWARE("UnpublishFirmware"),
    SET_VARIABLE_MONITORING("SetVariableMonitoring"),
    SET_MONITORING_LEVEL("SetMonitoringLevel"),
    PUBLISH_FIRMWARE("PublishFirmware"),
    SET_NETWORK_PROFILE("SetNetworkProfile"),
    GET_TRANSACTION_STATUS("GetTransactionStatus"),
    SET_MONITORING_BASE("SetMonitoringBase"),
    GET_DISPLAY_MESSAGES("GetDisplayMessages"),
    COST_UPDATED("CostUpdated"),
    SET_DISPLAYMESSAGE("setDisplayMessage"),
    DELETE_CERTIFICATE("deleteCertificate"),
    GET_MONITORING_REPORT("getMonitoringReport"),
    CLEAR_VARIABLE_MONITORING("clearVariableMonitoring")
}

