name: OCPP CI

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "**" ]

permissions:
    contents: read

jobs:
    build:

        concurrency: ocpp-ci

        runs-on: ubuntu-latest

        steps:
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'

            -   name: Checkout IZIVIA OCPP toolkit library code from GH
                uses: actions/checkout@v4

            -   name: Build OCPP toolkit with Gradle
                uses: gradle/gradle-build-action@v3
                with:
                    arguments: build
