name: OCPP CI

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "dev" ]

permissions:
    contents: read

jobs:
    build:

        concurrency: ocpp-ci

        runs-on: ubuntu-latest

        steps:
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Checkout IZIVIA OCPP toolkit library code from GH
                uses: actions/checkout@v3

            -   name: Build OCPP toolkit with Gradle
                uses: gradle/gradle-build-action@v2.2.1
                with:
                    gradle-version: 7.4.2
                    arguments: build
